# Generated by Django 5.2.15 on 2026-06-18 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('horas_totales', models.DecimalField(decimal_places=2, max_digits=7)),
                ('intensidad_diaria', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('politica_ausencia', models.CharField(choices=[('RECOMPUTAR', 'Recomputar fecha fin (preserva horas)'), ('REDUCIR', 'Reducir horas (preserva ventana)')], default='RECOMPUTAR', max_length=20)),
                ('tarifa_aplicada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('costo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('estado', models.CharField(choices=[('SOLICITADA', 'Solicitada'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('REVOCADA', 'Revocada'), ('INVALIDADA', 'Invalidada')], default='SOLICITADA', max_length=20)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='core.proyecto')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='core.recurso')),
                ('solicitada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignación',
                'verbose_name_plural': 'Asignaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREAR', 'Crear'), ('APROBAR', 'Aprobar'), ('RECHAZAR', 'Rechazar'), ('REVOCAR', 'Revocar'), ('INVALIDAR', 'Invalidar')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('detalle', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='log', to='assignments.asignacion')),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'ordering': ['timestamp'],
            },
        ),
    ]
