# Generated by Django 5.2.15 on 2026-06-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='horas_totales',
            field=models.PositiveIntegerField(help_text='Total de horas del recurso en el proyecto (ej: 40, 80, 160)'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='intensidad_diaria',
            field=models.DecimalField(decimal_places=1, help_text='Horas por día (ej: 4, 4.5, 8)', max_digits=4),
        ),
    ]
