# Generated by Django 5.2.15 on 2026-06-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_alter_asignacion_horas_totales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='dias_habiles',
            field=models.PositiveIntegerField(blank=True, help_text='Días hábiles de trabajo', null=True),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='modo_asignacion',
            field=models.CharField(choices=[('HORAS', 'Por horas totales'), ('DIAS', 'Por días hábiles'), ('RANGO', 'Por rango de fechas')], default='HORAS', max_length=10, verbose_name='Modo'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='horas_totales',
            field=models.PositiveIntegerField(blank=True, help_text='Total de horas (ej: 40, 80, 160)', null=True),
        ),
    ]
