# Generated by Django 5.2.15 on 2026-06-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_asignacion_dias_habiles_asignacion_modo_asignacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='jornada_completa',
            field=models.BooleanField(default=False, help_text='El recurso trabaja su jornada máxima cada día del rango (lun–jue 8.5 h, vie 8 h)'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='intensidad_diaria',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Horas por día (ej: 4, 4.5, 8)', max_digits=4, null=True),
        ),
    ]
