# Generated by Django 5.2.15 on 2026-06-24 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_asignacion_jornada_completa_and_more'),
        ('core', '0005_cluster_recurso_nro_persona_sap_recurso_clusters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='cluster',
            field=models.ForeignKey(blank=True, help_text='Cluster del recurso bajo el que opera esta asignación.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='core.cluster', verbose_name='Cluster'),
        ),
    ]
