# Generated by Django 5.2.15 on 2026-07-09 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_asignacion_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='serie',
            field=models.UUIDField(blank=True, db_index=True, help_text='Agrupa las asignaciones creadas por una misma solicitud recurrente.', null=True, verbose_name='Serie'),
        ),
    ]
