# Generated by Django 5.2.15 on 2026-07-09 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_asignacion_serie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='logauditoria',
            name='accion',
            field=models.CharField(choices=[('CREAR', 'Crear'), ('APROBAR', 'Aprobar'), ('RECHAZAR', 'Rechazar'), ('REVOCAR', 'Revocar'), ('INVALIDAR', 'Invalidar'), ('CEDER', 'Ceder horas'), ('ANULAR_CESION', 'Anular cesión')], max_length=20),
        ),
        migrations.CreateModel(
            name='CesionHoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Día laborado cuyas horas se ceden.')),
                ('horas', models.DecimalField(decimal_places=1, max_digits=4)),
                ('politica', models.CharField(choices=[('RECOMPUTAR', 'Recomputar fecha fin (preserva horas)'), ('REDUCIR', 'Reducir horas (preserva ventana)')], help_text='RECOMPUTAR: la original extiende fecha_fin para recuperar las horas. REDUCIR: la original baja su total de horas.', max_length=20)),
                ('tarifa_hora', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_fin_original', models.DateField(blank=True, help_text='fecha_fin de la asignación origen antes de recomputar (para poder anular).', null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('anulada_en', models.DateTimeField(blank=True, null=True)),
                ('asignacion_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cesiones_recibidas', to='assignments.asignacion')),
                ('asignacion_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cesiones_realizadas', to='assignments.asignacion')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cesiones_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cesión de horas',
                'verbose_name_plural': 'Cesiones de horas',
                'ordering': ['-creado_en'],
            },
        ),
    ]
