# Generated by Django 5.2.15 on 2026-07-15 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0007_alter_logauditoria_accion_cesionhoras'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='logauditoria',
            name='accion',
            field=models.CharField(choices=[('CREAR', 'Crear'), ('APROBAR', 'Aprobar'), ('RECHAZAR', 'Rechazar'), ('REVOCAR', 'Revocar'), ('INVALIDAR', 'Invalidar'), ('CEDER', 'Ceder horas'), ('ANULAR_CESION', 'Anular cesión'), ('RECOMPUTO_TARIFA', 'Recomputo por cambio de tarifa')], max_length=20),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
