services:
  web:
    build: ./backend
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.local
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
