# Generated by Django 5.2.15 on 2026-06-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='recurso',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='recursos', to='core.skill'),
        ),
    ]
