# Generated by Django 5.2.15 on 2026-06-24 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_skill_descripcion_recursosskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(blank=True, max_length=100, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Cluster',
                'verbose_name_plural': 'Clusters',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='recurso',
            name='nro_persona_sap',
            field=models.CharField(blank=True, help_text='Identificador único de persona en SAP (ej: 30011076).', max_length=20, null=True, unique=True, verbose_name='N° persona SAP'),
        ),
        migrations.AddField(
            model_name='recurso',
            name='clusters',
            field=models.ManyToManyField(blank=True, related_name='recursos', to='core.cluster', verbose_name='Clusters'),
        ),
        migrations.CreateModel(
            name='TarifaVigente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_hora', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tarifa €/h')),
                ('fecha_desde', models.DateField(help_text='Fecha a partir de la cual aplica esta tarifa.', verbose_name='Vigente desde')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifas', to='core.recurso')),
            ],
            options={
                'verbose_name': 'Tarifa',
                'verbose_name_plural': 'Tarifas',
                'ordering': ['-fecha_desde'],
                'unique_together': {('recurso', 'fecha_desde')},
            },
        ),
    ]
