# Generated by Django 5.2.15 on 2026-07-09 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_proyecto_codigo_pep'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='grafo',
            field=models.CharField(blank=True, help_text='Grafo (orden de red) del proyecto en SAP (ej: 4000123456). Único cuando se informa.', max_length=50, null=True, unique=True, verbose_name='Grafo'),
        ),
    ]
