# Generated by Django 5.2.15 on 2026-07-09 01:51

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_proyecto_grafo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='codigo',
            field=models.CharField(help_text='Código del proyecto en SAP (ej: V-00869252/D).', max_length=50, unique=True, validators=[apps.core.validators.validar_codigo_proyecto]),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='codigo_pep',
            field=models.CharField(blank=True, help_text='Elemento PEP del proyecto en SAP (ej: L-00869252/A). Único cuando se informa.', max_length=50, null=True, unique=True, validators=[apps.core.validators.validar_codigo_pep], verbose_name='Código PEP'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='grafo',
            field=models.CharField(blank=True, help_text='Grafo (orden de red) del proyecto en SAP (ej: 2000269630). Único cuando se informa.', max_length=50, null=True, unique=True, validators=[apps.core.validators.validar_grafo], verbose_name='Grafo'),
        ),
    ]
