# Generated by Django 5.2.17 on 2026-08-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_proyecto_codigo_alter_proyecto_codigo_pep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='facturable',
            field=models.BooleanField(default=True, help_text='Las horas de este proyecto se cobran a un cliente. Desmarcar en los proyectos internos (formación interna, gestión departamental...): siguen siendo proyectos normales y hay que darlos de alta igual, pero no entran en el informe de horas facturables.'),
        ),
    ]
