# Generated by Django 5.2.15 on 2026-06-18 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaNoLaborable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Día No Laborable',
                'verbose_name_plural': 'Días No Laborables',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Indisponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('tipo', models.CharField(choices=[('VACACION', 'Vacación'), ('PERMISO', 'Permiso')], max_length=20)),
                ('origen', models.CharField(choices=[('MANUAL', 'Manual'), ('SAP', 'SAP')], default='MANUAL', max_length=10)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indisponibilidades', to='core.recurso')),
            ],
            options={
                'verbose_name': 'Indisponibilidad',
                'verbose_name_plural': 'Indisponibilidades',
                'ordering': ['fecha_inicio'],
            },
        ),
    ]
