# Generated by Django 5.2.17 on 2026-08-26 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def aprobar_existentes(apps, schema_editor):
    """Las indisponibilidades que ya existían pasan a APROBADA.

    El campo nace con default PENDIENTE, que es lo correcto para las novedades
    nuevas. Pero aplicarlo a las filas ya cargadas dejaría de golpe a toda la
    plantilla como disponible durante sus vacaciones, porque el motor de
    calendario solo cuenta las aprobadas — y sin ningún error visible: la gente
    aparecería libre para asignar en días que no lo está.

    Todo lo anterior a este flujo lo cargó un PM, un Admin o la sincronización
    de SAP, así que ya estaba aprobado de hecho.
    """
    Indisponibilidad = apps.get_model("calendar_engine", "Indisponibilidad")
    Indisponibilidad.objects.all().update(estado="APROBADA")


def revertir(apps, schema_editor):
    """La reversión no hace nada: el campo entero desaparece al deshacer."""


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_engine', '0001_initial'),
        ('core', '0008_alter_proyecto_codigo_alter_proyecto_codigo_pep_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='indisponibilidad',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de aprobación'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', help_text='Solo las APROBADAS descuentan capacidad del recurso.', max_length=20),
        ),
        migrations.AddField(
            model_name='indisponibilidad',
            name='motivo',
            field=models.CharField(blank=True, help_text='Nota de quien solicita la novedad (opcional).', max_length=200),
        ),
        migrations.AddField(
            model_name='indisponibilidad',
            name='motivo_rechazo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='indisponibilidad',
            name='revisada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indisponibilidad',
            name='revisada_por',
            field=models.ForeignKey(blank=True, help_text='Admin que aprobó o rechazó la novedad.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='novedades_revisadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='indisponibilidad',
            name='solicitada_por',
            field=models.ForeignKey(blank=True, help_text='Vacío en las cargadas antes de este flujo o sincronizadas desde SAP.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='novedades_solicitadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='indisponibilidad',
            index=models.Index(fields=['recurso', 'estado'], name='calendar_en_recurso_1984cb_idx'),
        ),
        # Va después de AddField: la columna tiene que existir para poder
        # rellenarla.
        migrations.RunPython(aprobar_existentes, revertir),
    ]
