# Generated by Django 5.2.17 on 2026-08-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_engine', '0002_indisponibilidad_estado_indisponibilidad_motivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indisponibilidad',
            name='tipo',
            field=models.CharField(choices=[('VACACION', 'Vacaciones'), ('PERMISO', 'Permiso')], max_length=20),
        ),
    ]
