# Generated by Django 5.2.17 on 2026-09-09 03:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0012_proyecto_interno_con_equipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloqueante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('necesito', models.CharField(help_text='En una frase. Lo va a leer alguien que no tiene tu contexto.', max_length=300, verbose_name='Qué necesito')),
                ('bloquea_nombre', models.CharField(blank=True, help_text='Solo si quien puede resolverlo no tiene cuenta en la plataforma.', max_length=120, verbose_name='Otra persona')),
                ('mientras_tanto', models.CharField(blank=True, help_text='Opcional. Sirve para saber si el bloqueo te dejó parado del todo.', max_length=300, verbose_name='Qué haces mientras')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('resuelto_en', models.DateTimeField(blank=True, null=True)),
                ('como_se_resolvio', models.CharField(blank=True, max_length=300)),
                ('bloquea_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bloqueantes_a_su_cargo', to=settings.AUTH_USER_MODEL, verbose_name='Quién puede resolverlo')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bloqueantes_reportados', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bloqueantes', to='core.proyecto')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bloqueantes', to='core.recurso')),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bloqueantes_resueltos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bloqueante',
                'verbose_name_plural': 'Bloqueantes',
                'ordering': ['resuelto_en', 'creado_en'],
                'indexes': [models.Index(fields=['recurso', 'resuelto_en'], name='seguimiento_recurso_e266d1_idx'), models.Index(fields=['resuelto_en', 'creado_en'], name='seguimiento_resuelt_97b203_idx')],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('direccion', models.CharField(choices=[('P2R', 'Del proyecto hacia la persona'), ('R2P', 'De la persona hacia el proyecto')], max_length=3)),
                ('momento', models.CharField(choices=[('SEMANAL', 'Seguimiento semanal'), ('CIERRE', 'Cierre de asignación')], default='SEMANAL', max_length=10)),
                ('fecha_observacion', models.DateField(default=django.utils.timezone.localdate)),
                ('situacion', models.CharField(blank=True, help_text='Cuándo y en qué contexto.', max_length=300)),
                ('conducta', models.TextField(blank=True, help_text='Qué hizo o dejó de hacer. Hechos, no adjetivos.', verbose_name='Conducta observada')),
                ('impacto', models.TextField(blank=True, help_text='Qué consecuencia tuvo. Sin esto no se entiende por qué importa.')),
                ('tipo', models.CharField(blank=True, choices=[('FORTALEZA', 'Fortaleza'), ('A_MEJORAR', 'A mejorar')], max_length=10)),
                ('dimension', models.CharField(blank=True, choices=[('COMUNICACION', 'Comunicación'), ('AUTONOMIA', 'Autonomía'), ('TECNICO', 'Conocimiento técnico'), ('PLANIFICACION', 'Planificación y estimación')], max_length=20)),
                ('claridad_objetivo', models.PositiveSmallIntegerField(blank=True, help_text='1 = no supe qué se esperaba · 5 = clarísimo desde el principio.', null=True, verbose_name='Claridad del objetivo')),
                ('tuve_que_intuir', models.BooleanField(blank=True, null=True)),
                ('que_intui', models.TextField(blank=True, verbose_name='Qué tuve que intuir')),
                ('horas_hasta_respuesta', models.PositiveIntegerField(blank=True, null=True, verbose_name='Horas hasta que me respondieron')),
                ('cambio_alcance', models.BooleanField(blank=True, null=True)),
                ('veces_cambio_alcance', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('que_ahorraria_tiempo', models.TextField(blank=True, verbose_name='Qué me habría ahorrado tiempo')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks_escritos', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks', to='core.proyecto')),
                ('recurso', models.ForeignKey(help_text='La persona sobre la que, o desde la que, se observa.', on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks', to='core.recurso')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
                'ordering': ['-fecha_observacion', '-id'],
                'indexes': [models.Index(fields=['recurso', '-fecha_observacion'], name='seguimiento_recurso_41d023_idx'), models.Index(fields=['direccion', '-fecha_observacion'], name='seguimiento_direcci_aabc40_idx')],
            },
        ),
    ]
