# Generated by Django 5.2.17 on 2026-09-09 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='horas_hasta_respuesta',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='que_intui',
        ),
        migrations.AddField(
            model_name='bloqueante',
            name='rol_que_resuelve',
            field=models.CharField(choices=[('PM', 'Jefe de proyecto'), ('LIDER', 'Líder de equipo'), ('COMPANERO', 'Un compañero del equipo'), ('CLIENTE', 'Alguien del cliente'), ('ACCESOS', 'Accesos o soporte técnico'), ('OTRO', 'Otra persona')], default='OTRO', max_length=12, verbose_name='Rol que debe resolverlo'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='comentario',
            field=models.TextField(blank=True, help_text='Qué estuvo bien y qué puede mejorar.', verbose_name='Tu feedback para el proyecto'),
        ),
        migrations.AlterField(
            model_name='bloqueante',
            name='bloquea_nombre',
            field=models.CharField(blank=True, help_text='Opcional. Si sabes quién es en concreto, ayuda a reclamarlo.', max_length=120, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='bloqueante',
            name='bloquea_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bloqueantes_a_su_cargo', to=settings.AUTH_USER_MODEL, verbose_name='Persona concreta (deducida)'),
        ),
        migrations.AlterField(
            model_name='bloqueante',
            name='necesito',
            field=models.CharField(help_text='En una frase. Lo va a leer alguien que no tiene tu contexto.', max_length=300, verbose_name='Qué te está bloqueando'),
        ),
    ]
