# Generated by Django 5.2.17 on 2026-09-09 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0002_remove_feedback_horas_hasta_respuesta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='en_nombre_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks_transcritos', to=settings.AUTH_USER_MODEL, verbose_name='Observado por'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='autor',
            field=models.ForeignKey(help_text='Quien lo escribió en la aplicación.', on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks_escritos', to=settings.AUTH_USER_MODEL),
        ),
    ]
