# Generated by Django 5.2.17 on 2026-09-09 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_proyecto_interno_con_equipo'),
        ('seguimiento', '0003_feedback_en_nombre_de_alter_feedback_autor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccionDeSeguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('CONVERSACION', 'Conversación con la persona'), ('ESCALADO', 'Escalado al proyecto'), ('FORMACION', 'Formación o acompañamiento'), ('CAMBIO', 'Cambio de asignación o de alcance'), ('SIN_ACCION', 'Revisado, sin acción por ahora')], default='CONVERSACION', max_length=14)),
                ('texto', models.TextField(help_text='Qué decidiste y por qué. Lo va a leer quien herede este seguimiento.', verbose_name='Qué hiciste')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acciones_de_seguimiento', to=settings.AUTH_USER_MODEL)),
                ('feedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acciones', to='seguimiento.feedback', verbose_name='A raíz de')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acciones_seguimiento', to='core.recurso')),
            ],
            options={
                'verbose_name': 'Acción de seguimiento',
                'verbose_name_plural': 'Acciones de seguimiento',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['recurso', '-creado_en'], name='seguimiento_recurso_a60ee1_idx')],
            },
        ),
    ]
