# Generated by Django 5.2.15 on 2026-07-17 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CambioPasswordPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(blank=True, default='Credencial temporal: debe cambiarse en el primer inicio de sesión.', max_length=200)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cambio_password_pendiente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cambio de contraseña pendiente',
                'verbose_name_plural': 'Cambios de contraseña pendientes',
            },
        ),
    ]
