# Generated by Django 5.2.17 on 2026-08-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('requiere_proyecto', models.BooleanField(default=False, help_text='Si está marcado, al registrar horas hay que indicar a qué proyecto.')),
                ('activo', models.BooleanField(default=True, help_text='Desmarcar para retirarlo de los desplegables sin perder el histórico.')),
                ('orden', models.PositiveSmallIntegerField(default=100, help_text='Posición en el desplegable. Menor aparece primero.')),
            ],
            options={
                'verbose_name': 'Tipo de actividad',
                'verbose_name_plural': 'Tipos de actividad',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
