# Generated by Django 5.2.17 on 2026-08-26 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_proyecto_facturable'),
        ('legalizacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaLegalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('REGISTRADO', 'Registrado'), ('APROBADO', 'Aprobado')], default='ABIERTO', max_length=12)),
                ('total_horas', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('jornada_esperada', models.DecimalField(decimal_places=1, default=0, help_text='Jornada que regía ese día. Se guarda por si la jornada legal cambia después.', max_digits=4)),
                ('registrado_en', models.DateTimeField(blank=True, null=True)),
                ('aprobado_en', models.DateTimeField(blank=True, null=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dias_aprobados', to=settings.AUTH_USER_MODEL)),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dias_legalizados', to='core.recurso')),
            ],
            options={
                'verbose_name': 'Día legalizado',
                'verbose_name_plural': 'Días legalizados',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='RegistroHoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('horas', models.DecimalField(decimal_places=1, max_digits=4)),
                ('detalle', models.CharField(help_text='Qué se hizo. Es lo que permite legalizar estas horas después.', max_length=300)),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='legalizacion.dialegalizado')),
                ('proyecto', models.ForeignKey(blank=True, help_text='Obligatorio si el tipo de actividad lo exige; vacío en el resto.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros_horas', to='core.proyecto')),
                ('tipo_actividad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='legalizacion.tipoactividad')),
            ],
            options={
                'verbose_name': 'Registro de horas',
                'verbose_name_plural': 'Registros de horas',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='dialegalizado',
            index=models.Index(fields=['recurso', 'fecha'], name='legalizacio_recurso_09764f_idx'),
        ),
        migrations.AddIndex(
            model_name='dialegalizado',
            index=models.Index(fields=['estado', 'fecha'], name='legalizacio_estado_ca95f1_idx'),
        ),
        migrations.AddConstraint(
            model_name='dialegalizado',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('recurso', 'fecha'), name='un_dia_legalizado_por_recurso_y_fecha'),
        ),
    ]
