# Generated by Django 5.2.17 on 2026-08-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legalizacion', '0002_dialegalizado_registrohoras_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoactividad',
            name='descripcion',
            field=models.CharField(blank=True, help_text='Cuándo usar esta actividad. Se muestra al elegirla, y es lo que evita que dos categorías parecidas se rellenen al azar.', max_length=300),
        ),
    ]
