# Generated by Django 5.2.17 on 2026-08-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legalizacion', '0003_tipoactividad_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialegalizado',
            name='motivo_devolucion',
            field=models.CharField(blank=True, help_text='Por qué se devolvió el día para corregir. Lo ve quien lo registró: devolver sin decir qué está mal solo genera un segundo intento a ciegas.', max_length=300),
        ),
    ]
