# Generated by Django 5.2.17 on 2026-08-31 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legalizacion', '0004_dialegalizado_motivo_devolucion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registrohoras',
            name='aprobado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrohoras',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='renglones_aprobados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrohoras',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de aprobación'), ('APROBADO', 'Aprobado'), ('DEVUELTO', 'Devuelto para corregir')], default='PENDIENTE', max_length=10),
        ),
        migrations.AddField(
            model_name='registrohoras',
            name='motivo_devolucion',
            field=models.CharField(blank=True, help_text='Por qué se devolvió este renglón. Lo ve quien lo registró: devolver sin decir qué está mal solo genera un segundo intento a ciegas.', max_length=300),
        ),
    ]
