# Generated by Django 5.2.17 on 2026-09-02 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legalizacion', '0007_rellenar_firma_de_dias_aprobados'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrohoras',
            name='aprobacion_forzada',
            field=models.BooleanField(default=False, help_text='Se firmó teniendo avisos del triaje.'),
        ),
        migrations.AddField(
            model_name='registrohoras',
            name='motivo_aprobacion',
            field=models.CharField(blank=True, help_text='Por qué se firmó pese a los avisos. Solo se pide al firmar un día entero de una vez.', max_length=300),
        ),
        migrations.AddField(
            model_name='registrohoras',
            name='senales_anuladas',
            field=models.JSONField(blank=True, default=list, help_text='Códigos de los avisos que llevaba el renglón al firmarlo.'),
        ),
    ]
