# Generated by Django 5.2.17 on 2026-09-07 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legalizacion', '0008_registrohoras_aprobacion_forzada_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReaperturaDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('estado_anterior', models.CharField(max_length=12)),
                ('motivo', models.CharField(help_text='Por qué hubo que reabrirlo. Lo ve quien registró el día.', max_length=300)),
                ('firmas_revertidas', models.JSONField(blank=True, default=list)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dias_reabiertos', to=settings.AUTH_USER_MODEL)),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reaperturas', to='legalizacion.dialegalizado')),
            ],
            options={
                'verbose_name': 'Reapertura de día',
                'verbose_name_plural': 'Reaperturas de día',
                'ordering': ['-creado_en'],
            },
        ),
    ]
