# Generated by Django 5.2.17 on 2026-09-08 00:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legalizacion', '0010_reapertura_append_only_trigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrosLegalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_exigencia', models.DateField(default=datetime.date(2026, 9, 1), help_text='Primer día que la plataforma reclama como pendiente. Los anteriores no se listan ni se persiguen. Sí se pueden legalizar a mano si hace falta recuperar alguno.', verbose_name='Se exigen días desde')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parámetros de legalización',
                'verbose_name_plural': 'Parámetros de legalización',
            },
        ),
    ]
